## Calcul Matriciel

**Sujet : Analyse de températures.**

Imagine que tu as relevé les températures de 3 villes sur 7 jours (une matrice 3x7).

**Objectifs :**

1. **Inspection** : Affiche la forme (`shape`) et le type de données de la matrice.
2. **Écrêtage** : Remplacer toutes les valeurs inférieures à 20 par la valeur 20 
3. **Moyennes** :
    * Calcule la température moyenne globale.
    * Calcule la moyenne de chaque ville (utilise `axis=1`).

4. **Seuil** : Identifie tous les jours où la température a dépassé 30 degrés (indexation booléenne).
5. **Normalisation** : Convertis toutes les températures en degrés Fahrenheit () de manière vectorisée.

In [77]:
import numpy as np

# Données : 3 villes (lignes), 7 jours (colonnes)
temperatures = np.array([
    [22, 25, 19, 30, 32, 28, 24], # Ville A
    [15, 18, 21, 20, 19, 17, 16], # Ville B
    [31, 34, 33, 29, 30, 35, 32]  # Ville C
])

temperatures

array([[22, 25, 19, 30, 32, 28, 24],
       [15, 18, 21, 20, 19, 17, 16],
       [31, 34, 33, 29, 30, 35, 32]])

1. **Inspection** : Affiche la forme (`shape`) et le type de données de la matrice.

In [78]:
print(temperatures.shape, temperatures.dtype)

(3, 7) int64


2. **Écrêtage** : Remplacer toutes les valeurs inférieures à 20 par la valeur 20 

In [79]:
# data = np.clip(temperatures, min=20)

temperatures[temperatures < 20] = 20

temperatures


array([[22, 25, 20, 30, 32, 28, 24],
       [20, 20, 21, 20, 20, 20, 20],
       [31, 34, 33, 29, 30, 35, 32]])

3. **Moyennes** :
    * Calcule la température moyenne globale.
    * Calcule la moyenne de chaque ville (utilise `axis=1`).

In [80]:
moyenne = temperatures.mean()

print("Temperature moyenne global :", moyenne)

moyenne_par_ville = temperatures.mean(axis=1)

print("Temperature moyenne par ville :", moyenne_par_ville)

Temperature moyenne global : 26.0
Temperature moyenne par ville : [25.85714286 20.14285714 32.        ]


4. **Seuil** : Identifie tous les jours où la température a dépassé 30 degrés (indexation booléenne).

In [81]:
temperatures[temperatures > 30]

array([32, 31, 34, 33, 35, 32])

5. **Normalisation** : Convertis toutes les températures en degrés Fahrenheit () de manière vectorisée.

In [82]:
temperatures = temperatures * 1.8 + 32

temperatures

array([[71.6, 77. , 68. , 86. , 89.6, 82.4, 75.2],
       [68. , 68. , 69.8, 68. , 68. , 68. , 68. ],
       [87.8, 93.2, 91.4, 84.2, 86. , 95. , 89.6]])